ERROR:root:unsupported operand type(s) for /: 'NoneType' and 'int'
DEBUG:django.template:Exception while resolving variable 'exception_notes' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py", line 534, in generate_report
    'apcPI': cotizacion.apcPI / 100,
             ~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py", line 920, in generate_report
    return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)
                                                                            ^^^^^^^^^
UnboundLocalError: cannot access local variable 'resultado' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [exception_notes] in [{'True': True, 'False': False, 'None': None}, {'is_email': False, 'unicode_hint': '', 'frames': [{'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x112521ec0>, 'type': 'user', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py', 'function': 'generate_report', 'lineno': 534, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('numero_cotizacion', '129'), ('cotizacion', '<Cotizacion: 129 - asd - asd>'), ('error_message', '"unsupported operand type(s) for /: \'NoneType\' and \'int\'"')], 'id': 4602339008, 'pre_context': ["            'oficial': cotizacion.oficial,", "            'nombreCliente': cotizacion.nombreCliente,", "            'cedulaCliente': cotizacion.cedulaCliente,", "            'tipoDocumento': cotizacion.tipoDocumento,", "            'edad': cotizacion.edad,", "            'sexo': cotizacion.sexo,", "            'apcScore': cotizacion.apcScore,"], 'context_line': "            'apcPI': cotizacion.apcPI / 100,", 'post_context': ["            'cotPlazoPago': cotizacion.plazoPago,", "            'r1': cotizacion.r1,", "            'abonoPorcentaje': cotizacion.abonoPorcentaje,", "            'abono': cotizacion.abono,", "            'cashback': cotizacion.cashback,", "            'valorAuto': cotizacion.valorAuto,"], 'pre_context_lineno': 527, 'colno': '\n                          ^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n             ^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x1124c2900>, 'type': 'django', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/exception.py', 'function': 'inner', 'lineno': 55, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('exc', 'UnboundLocalError("cannot access local variable \'resultado\' where it is not associated with a value")'), ('get_response', '<bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x110d59450>>')], 'id': 4601948416, 'pre_context': ['', '        return inner', '    else:', '', '        @wraps(get_response)', '        def inner(request):', '            try:'], 'context_line': '                response = get_response(request)', 'post_context': ['            except Exception as exc:', '                response = response_for_exception(request, exc)', '            return response', '', '        return inner', ''], 'pre_context_lineno': 48, 'colno': '\n                               ^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x11240fd40>, 'type': 'django', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/base.py', 'function': '_get_response', 'lineno': 197, 'vars': [('self', '<django.core.handlers.wsgi.WSGIHandler object at 0x110d59450>'), ('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('response', 'None'), ('callback', '<function generate_report at 0x110aed760>'), ('callback_args', '()'), ('callback_kwargs', "{'numero_cotizacion': 129}"), ('middleware_method', '<bound method CsrfViewMiddleware.process_view of <CsrfViewMiddleware get_response=convert_exception_to_response.<locals>.inner>>'), ('wrapped_callback', '<function generate_report at 0x110aed760>')], 'id': 4601216320, 'pre_context': ['', '        if response is None:', '            wrapped_callback = self.make_view_atomic(callback)', '            # If it is an asynchronous view, run it in a subthread.', '            if iscoroutinefunction(wrapped_callback):', '                wrapped_callback = async_to_sync(wrapped_callback)', '            try:'], 'context_line': '                response = wrapped_callback(request, *callback_args, **callback_kwargs)', 'post_context': ['            except Exception as e:', '                response = self.process_exception_by_middleware(e, request)', '                if response is None:', '                    raise', '', '        # Complain if the view returned None (a common error).'], 'pre_context_lineno': 190, 'colno': '\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x1120c3e40>, 'type': 'django', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py', 'function': '_view_wrapper', 'lineno': 60, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('args', '()'), ('kwargs', "{'numero_cotizacion': 129}"), ('test_pass', 'True'), ('_redirect_to_login', '<function user_passes_test.<locals>.decorator.<locals>._redirect_to_login at 0x110aed6c0>'), ('test_func', '<function login_required.<locals>.<lambda> at 0x110aed580>'), ('view_func', '<function generate_report at 0x110aed4e0>')], 'id': 4597759552, 'pre_context': ['            def _view_wrapper(request, *args, **kwargs):', '                if asyncio.iscoroutinefunction(test_func):', '                    test_pass = async_to_sync(test_func)(request.user)', '                else:', '                    test_pass = test_func(request.user)', '', '                if test_pass:'], 'context_line': '                    return view_func(request, *args, **kwargs)', 'post_context': ['                return _redirect_to_login(request)', '', '        # Attributes used by LoginRequiredMiddleware.', '        _view_wrapper.login_url = login_url', '        _view_wrapper.redirect_field_name = redirect_field_name', ''], 'pre_context_lineno': 53, 'colno': '\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x110b9a0c0>, 'type': 'user', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py', 'function': 'generate_report', 'lineno': 920, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('numero_cotizacion', '129'), ('cotizacion', '<Cotizacion: 129 - asd - asd>'), ('error_message', '"unsupported operand type(s) for /: \'NoneType\' and \'int\'"')], 'id': 4575568064, 'pre_context': ["            response = HttpResponse(f.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')", "            response['Content-Disposition'] = f'attachment; filename={filename}'", '            return response', '    ', '    except Exception as e:', '        error_message = str(e)', '        log_error(error_message, request.user.username)'], 'context_line': "        return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)", 'post_context': ['        ', '', '@login_required', 'def main_menu(request):', "    return render(request, 'main_menu.html')", ''], 'pre_context_lineno': 913, 'colno': '\n                                                                                     ^^^^^^^^^', 'tb_area_colno': '\n                                                                            ^^^^^^^^^'}], 'request': <WSGIRequest: GET '/generate_report/129/'>, 'request_meta': {'MallocNanoZone': '0', 'USER': 'andresrdrgz_', 'COMMAND_MODE': 'unix2003', '__CFBundleIdentifier': 'com.microsoft.VSCode', 'PATH': '/Users/andresrdrgz_/.vscode/extensions/ms-python.python-2024.22.1-darwin-arm64/python_files/deactivate/zsh:/Users/andresrdrgz_/Documents/PACIFICO/venv/bin:/Users/andresrdrgz_/.vscode/extensions/ms-python.python-2024.22.0-darwin-arm64/python_files/deactivate/zsh:/Users/andresrdrgz_/Documents/PACIFICO/venv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/andresrdrgz_/.vscode/extensions/ms-python.python-2024.22.1-darwin-arm64/python_files/deactivate/zsh:/Users/andresrdrgz_/Documents/PACIFICO/venv/bin:/Users/andresrdrgz_/anaconda3/bin:/Users/andresrdrgz_/anaconda3/condabin', 'LOGNAME': 'andresrdrgz_', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.fMRmES6zQK/Listeners', 'HOME': '/Users/andresrdrgz_', 'SHELL': '/bin/zsh', 'TMPDIR': '/var/folders/39/vbr6w96555nd1xmqx598z4r00000gn/T/', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'SHLVL': '1', 'PWD': '/Users/andresrdrgz_/Documents/PACIFICO/financiera', 'OLDPWD': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico', 'HOMEBREW_PREFIX': '/opt/homebrew', 'HOMEBREW_CELLAR': '/opt/homebrew/Cellar', 'HOMEBREW_REPOSITORY': '/opt/homebrew', 'INFOPATH': '/opt/homebrew/share/info:/opt/homebrew/share/info:', 'CONDA_EXE': '/Users/andresrdrgz_/anaconda3/bin/conda', '_CE_M': '', '_CE_CONDA': '', 'CONDA_PYTHON_EXE': '/Users/andresrdrgz_/anaconda3/bin/python', 'CONDA_SHLVL': '1', 'CONDA_PREFIX': '/Users/andresrdrgz_/anaconda3', 'CONDA_DEFAULT_ENV': 'base', 'CONDA_PROMPT_MODIFIER': '(base) ', 'TERM_PROGRAM': 'vscode', 'TERM_PROGRAM_VERSION': '1.96.2', 'LANG': 'en_US.UTF-8', 'COLORTERM': 'truecolor', 'GIT_ASKPASS': '********************', 'VSCODE_GIT_ASKPASS_NODE': '********************', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS': '********************', 'VSCODE_GIT_ASKPASS_MAIN': '********************', 'VSCODE_GIT_IPC_HANDLE': '/var/folders/39/vbr6w96555nd1xmqx598z4r00000gn/T/vscode-git-910ceb7537.sock', 'VIRTUAL_ENV': '/Users/andresrdrgz_/Documents/PACIFICO/venv', 'VIRTUAL_ENV_PROMPT': 'venv', 'VSCODE_INJECTION': '1', 'ZDOTDIR': '/Users/andresrdrgz_', 'USER_ZDOTDIR': '/Users/andresrdrgz_', 'TERM': 'xterm-256color', 'PS1': 'venv(base) %n@%m %1~ %# ', '_': '/Users/andresrdrgz_/Documents/PACIFICO/venv/bin/python', 'DJANGO_SETTINGS_MODULE': 'financiera.settings', 'TZ': 'UTC', 'RUN_MAIN': 'true', 'SERVER_NAME': '1.0.0.127.in-addr.arpa', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/generate_report/129/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_SEC_CH_UA': '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"', 'HTTP_SEC_CH_UA_MOBILE': '?0', 'HTTP_SEC_CH_UA_PLATFORM': '"macOS"', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 'HTTP_SEC_FETCH_SITE': 'same-origin', 'HTTP_SEC_FETCH_MODE': 'navigate', 'HTTP_SEC_FETCH_USER': '?1', 'HTTP_SEC_FETCH_DEST': 'document', 'HTTP_REFERER': 'http://127.0.0.1:8000/cotizacion/129/', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br, zstd', 'HTTP_ACCEPT_LANGUAGE': 'es-ES,es;q=0.9,en;q=0.8', 'HTTP_COOKIE': '********************', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x112018550>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>, 'CSRF_COOKIE': 'Gk0uqZiXrv9YPTO2H7N8lvADTSZSkvRE'}, 'request_COOKIES_items': dict_items([('localauth', 'localapif6f4b27de3df18d:'), ('isNotIncognito', 'true'), ('_ga', 'GA1.1.377595100.1724081623'), ('csrftoken', '********************'), ('sessionid', '********************')]), 'user_str': 'arodriguez', 'filtered_POST_items': [], 'settings': {'ABSOLUTE_URL_OVERRIDES': {}, 'ADMINS': [], 'ALLOWED_HOSTS': ['*'], 'APPEND_SLASH': True, 'AUTHENTICATION_BACKENDS': ['django.contrib.auth.backends.ModelBackend'], 'AUTH_PASSWORD_VALIDATORS': '********************', 'AUTH_USER_MODEL': 'auth.User', 'BASE_DIR': PosixPath('/Users/andresrdrgz_/Documents/PACIFICO/financiera'), 'CACHES': {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}, 'CACHE_MIDDLEWARE_ALIAS': 'default', 'CACHE_MIDDLEWARE_KEY_PREFIX': '********************', 'CACHE_MIDDLEWARE_SECONDS': 600, 'CSRF_COOKIE_AGE': 31449600, 'CSRF_COOKIE_DOMAIN': None, 'CSRF_COOKIE_HTTPONLY': False, 'CSRF_COOKIE_NAME': 'csrftoken', 'CSRF_COOKIE_PATH': '/', 'CSRF_COOKIE_SAMESITE': 'Lax', 'CSRF_COOKIE_SECURE': False, 'CSRF_FAILURE_VIEW': 'django.views.csrf.csrf_failure', 'CSRF_HEADER_NAME': 'HTTP_X_CSRFTOKEN', 'CSRF_TRUSTED_ORIGINS': ['https://cotfid.fpacifico.com', 'http://cotfid.fpacifico.com', 'http://localhost:8000', 'http://cotfid.fpacifico.com:8000'], 'CSRF_USE_SESSIONS': False, 'DATABASES': {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': PosixPath('/Users/andresrdrgz_/Documents/PACIFICO/financiera/db.sqlite3'), 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'USER': '', 'PASSWORD': '********************', 'HOST': '', 'PORT': '', 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}, 'DATABASE_ROUTERS': [], 'DATA_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'DATA_UPLOAD_MAX_NUMBER_FIELDS': 1000, 'DATA_UPLOAD_MAX_NUMBER_FILES': 100, 'DATETIME_FORMAT': 'N j, Y, P', 'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M'], 'DATE_FORMAT': 'N j, Y', 'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'], 'DEBUG': True, 'DEBUG_PROPAGATE_EXCEPTIONS': False, 'DECIMAL_SEPARATOR': '.', 'DEFAULT_AUTO_FIELD': 'django.db.models.BigAutoField', 'DEFAULT_CHARSET': 'utf-8', 'DEFAULT_EXCEPTION_REPORTER': 'django.views.debug.ExceptionReporter', 'DEFAULT_EXCEPTION_REPORTER_FILTER': 'django.views.debug.SafeExceptionReporterFilter', 'DEFAULT_FROM_EMAIL': 'webmaster@localhost', 'DEFAULT_INDEX_TABLESPACE': '', 'DEFAULT_TABLESPACE': '', 'DISALLOWED_USER_AGENTS': [], 'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend', 'EMAIL_HOST': 'localhost', 'EMAIL_HOST_PASSWORD': '********************', 'EMAIL_HOST_USER': '', 'EMAIL_PORT': 25, 'EMAIL_SSL_CERTFILE': None, 'EMAIL_SSL_KEYFILE': '********************', 'EMAIL_SUBJECT_PREFIX': '[Django] ', 'EMAIL_TIMEOUT': None, 'EMAIL_USE_LOCALTIME': False, 'EMAIL_USE_SSL': False, 'EMAIL_USE_TLS': False, 'EXCEL_FILE_PATH': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/financiera/pacifico/fideicomiso/patronos.xlsx', 'FILE_UPLOAD_DIRECTORY_PERMISSIONS': None, 'FILE_UPLOAD_HANDLERS': ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'], 'FILE_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'FILE_UPLOAD_PERMISSIONS': 420, 'FILE_UPLOAD_TEMP_DIR': None, 'FIRST_DAY_OF_WEEK': 0, 'FIXTURE_DIRS': [], 'FORCE_SCRIPT_NAME': None, 'FORMAT_MODULE_PATH': None, 'FORMS_URLFIELD_ASSUME_HTTPS': False, 'FORM_RENDERER': 'django.forms.renderers.DjangoTemplates', 'IGNORABLE_404_URLS': [], 'INSTALLED_APPS': ['unfold', 'unfold.contrib.filters', 'unfold.contrib.forms', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'pacifico'], 'INTERNAL_IPS': [], 'LANGUAGES': [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], 'LANGUAGES_BIDI': ['he', 'ar', 'ar-dz', 'ckb', 'fa', 'ug', 'ur'], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_COOKIE_AGE': None, 'LANGUAGE_COOKIE_DOMAIN': None, 'LANGUAGE_COOKIE_HTTPONLY': False, 'LANGUAGE_COOKIE_NAME': 'django_language', 'LANGUAGE_COOKIE_PATH': '/', 'LANGUAGE_COOKIE_SAMESITE': None, 'LANGUAGE_COOKIE_SECURE': False, 'LOCALE_PATHS': [], 'LOGGING': {'version': 1, 'disable_existing_loggers': False, 'handlers': {'file': {'level': 'DEBUG', 'class': 'logging.FileHandler', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/debug.log'}}, 'loggers': {'django': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': True}}}, 'LOGGING_CONFIG': 'logging.config.dictConfig', 'LOGIN_REDIRECT_URL': 'main_menu', 'LOGIN_URL': 'login', 'LOGOUT_REDIRECT_URL': None, 'MANAGERS': [], 'MEDIA_ROOT': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/media', 'MEDIA_URL': '/media/', 'MESSAGE_STORAGE': 'django.contrib.messages.storage.fallback.FallbackStorage', 'MIDDLEWARE': ['django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware'], 'MIGRATION_MODULES': {}, 'MONTH_DAY_FORMAT': 'F j', 'NUMBER_GROUPING': 0, 'PASSWORD_HASHERS': '********************', 'PASSWORD_RESET_TIMEOUT': '********************', 'PREPEND_WWW': False, 'ROOT_URLCONF': 'financiera.urls', 'SECRET_KEY': '********************', 'SECRET_KEY_FALLBACKS': '********************', 'SECURE_CONTENT_TYPE_NOSNIFF': True, 'SECURE_CROSS_ORIGIN_OPENER_POLICY': 'same-origin', 'SECURE_HSTS_INCLUDE_SUBDOMAINS': False, 'SECURE_HSTS_PRELOAD': False, 'SECURE_HSTS_SECONDS': 0, 'SECURE_PROXY_SSL_HEADER': None, 'SECURE_REDIRECT_EXEMPT': [], 'SECURE_REFERRER_POLICY': 'same-origin', 'SECURE_SSL_HOST': None, 'SECURE_SSL_REDIRECT': False, 'SERVER_EMAIL': 'root@localhost', 'SESSION_CACHE_ALIAS': 'default', 'SESSION_COOKIE_AGE': 1209600, 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_NAME': 'sessionid', 'SESSION_COOKIE_PATH': '/', 'SESSION_COOKIE_SAMESITE': 'Lax', 'SESSION_COOKIE_SECURE': False, 'SESSION_ENGINE': 'django.contrib.sessions.backends.db', 'SESSION_EXPIRE_AT_BROWSER_CLOSE': False, 'SESSION_FILE_PATH': None, 'SESSION_SAVE_EVERY_REQUEST': False, 'SESSION_SERIALIZER': 'django.contrib.sessions.serializers.JSONSerializer', 'SETTINGS_MODULE': 'financiera.settings', 'SHORT_DATETIME_FORMAT': 'm/d/Y P', 'SHORT_DATE_FORMAT': 'm/d/Y', 'SIGNING_BACKEND': 'django.core.signing.TimestampSigner', 'SILENCED_SYSTEM_CHECKS': [], 'STATICFILES_DIRS': ['/Users/andresrdrgz_/Documents/PACIFICO/financiera/static/insumos', '/Users/andresrdrgz_/Documents/PACIFICO/financiera/static/images'], 'STATICFILES_FINDERS': ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'], 'STATICFILES_STORAGE': 'whitenoise.storage.CompressedManifestStaticFilesStorage', 'STATIC_ROOT': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/staticfiles', 'STATIC_URL': '/static/', 'STORAGES': {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'}, 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}, 'TEMPLATES': [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}], 'TEST_NON_SERIALIZED_APPS': [], 'TEST_RUNNER': 'django.test.runner.DiscoverRunner', 'THOUSAND_SEPARATOR': ',', 'TIME_FORMAT': 'P', 'TIME_INPUT_FORMATS': ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'], 'TIME_ZONE': 'UTC', 'USE_I18N': True, 'USE_THOUSAND_SEPARATOR': False, 'USE_TZ': True, 'USE_X_FORWARDED_HOST': False, 'USE_X_FORWARDED_PORT': False, 'WSGI_APPLICATION': 'financiera.wsgi.application', 'X_FRAME_OPTIONS': 'DENY', 'YEAR_MONTH_FORMAT': 'F Y'}, 'sys_executable': '/Users/andresrdrgz_/Documents/PACIFICO/venv/bin/python', 'sys_version_info': '3.11.3', 'server_time': datetime.datetime(2025, 1, 6, 15, 0, 4, 400735, tzinfo=datetime.timezone.utc), 'django_version_info': '5.1.3', 'sys_path': ['/Users/andresrdrgz_/Documents/PACIFICO/financiera', '/Users/andresrdrgz_/anaconda3/lib/python311.zip', '/Users/andresrdrgz_/anaconda3/lib/python3.11', '/Users/andresrdrgz_/anaconda3/lib/python3.11/lib-dynload', '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages'], 'template_info': None, 'template_does_not_exist': False, 'postmortem': None, 'request_GET_items': <generator object MultiValueDict.items at 0x1120fc580>, 'request_FILES_items': <generator object MultiValueDict.items at 0x1120fcba0>, 'request_insecure_uri': 'http://127.0.0.1:8000/generate_report/129/', 'raising_view_name': 'pacifico.views.generate_report', 'exception_type': 'UnboundLocalError', 'exception_value': "cannot access local variable 'resultado' where it is not associated with a value", 'lastframe': {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x110b9a0c0>, 'type': 'user', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py', 'function': 'generate_report', 'lineno': 920, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('numero_cotizacion', '129'), ('cotizacion', '<Cotizacion: 129 - asd - asd>'), ('error_message', '"unsupported operand type(s) for /: \'NoneType\' and \'int\'"')], 'id': 4575568064, 'pre_context': ["            response = HttpResponse(f.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')", "            response['Content-Disposition'] = f'attachment; filename={filename}'", '            return response', '    ', '    except Exception as e:', '        error_message = str(e)', '        log_error(error_message, request.user.username)'], 'context_line': "        return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)", 'post_context': ['        ', '', '@login_required', 'def main_menu(request):', "    return render(request, 'main_menu.html')", ''], 'pre_context_lineno': 913, 'colno': '\n                                                                                     ^^^^^^^^^', 'tb_area_colno': '\n                                                                            ^^^^^^^^^'}}]
DEBUG:django.template:Exception while resolving variable 'exception_notes' in template 'unknown'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py", line 534, in generate_report
    'apcPI': cotizacion.apcPI / 100,
             ~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py", line 920, in generate_report
    return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)
                                                                            ^^^^^^^^^
UnboundLocalError: cannot access local variable 'resultado' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context.py", line 85, in __getitem__
    raise KeyError(key)
KeyError: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(
                                            ^^^^^^^^
AttributeError: type object 'Context' has no attribute 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'exception_notes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [exception_notes] in [{'True': True, 'False': False, 'None': None}, {'is_email': False, 'unicode_hint': '', 'frames': [{'exc_cause': None, 'exc_cause_explicit': None, 'tb': <traceback object at 0x112521ec0>, 'type': 'user', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py', 'function': 'generate_report', 'lineno': 534, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('numero_cotizacion', '129'), ('cotizacion', '<Cotizacion: 129 - asd - asd>'), ('error_message', '"unsupported operand type(s) for /: \'NoneType\' and \'int\'"')], 'id': 4602339008, 'pre_context': ["            'oficial': cotizacion.oficial,", "            'nombreCliente': cotizacion.nombreCliente,", "            'cedulaCliente': cotizacion.cedulaCliente,", "            'tipoDocumento': cotizacion.tipoDocumento,", "            'edad': cotizacion.edad,", "            'sexo': cotizacion.sexo,", "            'apcScore': cotizacion.apcScore,"], 'context_line': "            'apcPI': cotizacion.apcPI / 100,", 'post_context': ["            'cotPlazoPago': cotizacion.plazoPago,", "            'r1': cotizacion.r1,", "            'abonoPorcentaje': cotizacion.abonoPorcentaje,", "            'abono': cotizacion.abono,", "            'cashback': cotizacion.cashback,", "            'valorAuto': cotizacion.valorAuto,"], 'pre_context_lineno': 527, 'colno': '\n                          ^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n             ^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x1124c2900>, 'type': 'django', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/exception.py', 'function': 'inner', 'lineno': 55, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('exc', 'UnboundLocalError("cannot access local variable \'resultado\' where it is not associated with a value")'), ('get_response', '<bound method BaseHandler._get_response of <django.core.handlers.wsgi.WSGIHandler object at 0x110d59450>>')], 'id': 4601948416, 'pre_context': ['', '        return inner', '    else:', '', '        @wraps(get_response)', '        def inner(request):', '            try:'], 'context_line': '                response = get_response(request)', 'post_context': ['            except Exception as exc:', '                response = response_for_exception(request, exc)', '            return response', '', '        return inner', ''], 'pre_context_lineno': 48, 'colno': '\n                               ^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x11240fd40>, 'type': 'django', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/base.py', 'function': '_get_response', 'lineno': 197, 'vars': [('self', '<django.core.handlers.wsgi.WSGIHandler object at 0x110d59450>'), ('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('response', 'None'), ('callback', '<function generate_report at 0x110aed760>'), ('callback_args', '()'), ('callback_kwargs', "{'numero_cotizacion': 129}"), ('middleware_method', '<bound method CsrfViewMiddleware.process_view of <CsrfViewMiddleware get_response=convert_exception_to_response.<locals>.inner>>'), ('wrapped_callback', '<function generate_report at 0x110aed760>')], 'id': 4601216320, 'pre_context': ['', '        if response is None:', '            wrapped_callback = self.make_view_atomic(callback)', '            # If it is an asynchronous view, run it in a subthread.', '            if iscoroutinefunction(wrapped_callback):', '                wrapped_callback = async_to_sync(wrapped_callback)', '            try:'], 'context_line': '                response = wrapped_callback(request, *callback_args, **callback_kwargs)', 'post_context': ['            except Exception as e:', '                response = self.process_exception_by_middleware(e, request)', '                if response is None:', '                    raise', '', '        # Complain if the view returned None (a common error).'], 'pre_context_lineno': 190, 'colno': '\n                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x1120c3e40>, 'type': 'django', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py', 'function': '_view_wrapper', 'lineno': 60, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('args', '()'), ('kwargs', "{'numero_cotizacion': 129}"), ('test_pass', 'True'), ('_redirect_to_login', '<function user_passes_test.<locals>.decorator.<locals>._redirect_to_login at 0x110aed6c0>'), ('test_func', '<function login_required.<locals>.<lambda> at 0x110aed580>'), ('view_func', '<function generate_report at 0x110aed4e0>')], 'id': 4597759552, 'pre_context': ['            def _view_wrapper(request, *args, **kwargs):', '                if asyncio.iscoroutinefunction(test_func):', '                    test_pass = async_to_sync(test_func)(request.user)', '                else:', '                    test_pass = test_func(request.user)', '', '                if test_pass:'], 'context_line': '                    return view_func(request, *args, **kwargs)', 'post_context': ['                return _redirect_to_login(request)', '', '        # Attributes used by LoginRequiredMiddleware.', '        _view_wrapper.login_url = login_url', '        _view_wrapper.redirect_field_name = redirect_field_name', ''], 'pre_context_lineno': 53, 'colno': '\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', 'tb_area_colno': '\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'}, {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x110b9a0c0>, 'type': 'user', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py', 'function': 'generate_report', 'lineno': 920, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('numero_cotizacion', '129'), ('cotizacion', '<Cotizacion: 129 - asd - asd>'), ('error_message', '"unsupported operand type(s) for /: \'NoneType\' and \'int\'"')], 'id': 4575568064, 'pre_context': ["            response = HttpResponse(f.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')", "            response['Content-Disposition'] = f'attachment; filename={filename}'", '            return response', '    ', '    except Exception as e:', '        error_message = str(e)', '        log_error(error_message, request.user.username)'], 'context_line': "        return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)", 'post_context': ['        ', '', '@login_required', 'def main_menu(request):', "    return render(request, 'main_menu.html')", ''], 'pre_context_lineno': 913, 'colno': '\n                                                                                     ^^^^^^^^^', 'tb_area_colno': '\n                                                                            ^^^^^^^^^'}], 'request': <WSGIRequest: GET '/generate_report/129/'>, 'request_meta': {'MallocNanoZone': '0', 'USER': 'andresrdrgz_', 'COMMAND_MODE': 'unix2003', '__CFBundleIdentifier': 'com.microsoft.VSCode', 'PATH': '/Users/andresrdrgz_/.vscode/extensions/ms-python.python-2024.22.1-darwin-arm64/python_files/deactivate/zsh:/Users/andresrdrgz_/Documents/PACIFICO/venv/bin:/Users/andresrdrgz_/.vscode/extensions/ms-python.python-2024.22.0-darwin-arm64/python_files/deactivate/zsh:/Users/andresrdrgz_/Documents/PACIFICO/venv/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Applications/VMware Fusion.app/Contents/Public:/Users/andresrdrgz_/.vscode/extensions/ms-python.python-2024.22.1-darwin-arm64/python_files/deactivate/zsh:/Users/andresrdrgz_/Documents/PACIFICO/venv/bin:/Users/andresrdrgz_/anaconda3/bin:/Users/andresrdrgz_/anaconda3/condabin', 'LOGNAME': 'andresrdrgz_', 'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.fMRmES6zQK/Listeners', 'HOME': '/Users/andresrdrgz_', 'SHELL': '/bin/zsh', 'TMPDIR': '/var/folders/39/vbr6w96555nd1xmqx598z4r00000gn/T/', '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0', 'XPC_SERVICE_NAME': '0', 'XPC_FLAGS': '0x0', 'ORIGINAL_XDG_CURRENT_DESKTOP': 'undefined', 'SHLVL': '1', 'PWD': '/Users/andresrdrgz_/Documents/PACIFICO/financiera', 'OLDPWD': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico', 'HOMEBREW_PREFIX': '/opt/homebrew', 'HOMEBREW_CELLAR': '/opt/homebrew/Cellar', 'HOMEBREW_REPOSITORY': '/opt/homebrew', 'INFOPATH': '/opt/homebrew/share/info:/opt/homebrew/share/info:', 'CONDA_EXE': '/Users/andresrdrgz_/anaconda3/bin/conda', '_CE_M': '', '_CE_CONDA': '', 'CONDA_PYTHON_EXE': '/Users/andresrdrgz_/anaconda3/bin/python', 'CONDA_SHLVL': '1', 'CONDA_PREFIX': '/Users/andresrdrgz_/anaconda3', 'CONDA_DEFAULT_ENV': 'base', 'CONDA_PROMPT_MODIFIER': '(base) ', 'TERM_PROGRAM': 'vscode', 'TERM_PROGRAM_VERSION': '1.96.2', 'LANG': 'en_US.UTF-8', 'COLORTERM': 'truecolor', 'GIT_ASKPASS': '********************', 'VSCODE_GIT_ASKPASS_NODE': '********************', 'VSCODE_GIT_ASKPASS_EXTRA_ARGS': '********************', 'VSCODE_GIT_ASKPASS_MAIN': '********************', 'VSCODE_GIT_IPC_HANDLE': '/var/folders/39/vbr6w96555nd1xmqx598z4r00000gn/T/vscode-git-910ceb7537.sock', 'VIRTUAL_ENV': '/Users/andresrdrgz_/Documents/PACIFICO/venv', 'VIRTUAL_ENV_PROMPT': 'venv', 'VSCODE_INJECTION': '1', 'ZDOTDIR': '/Users/andresrdrgz_', 'USER_ZDOTDIR': '/Users/andresrdrgz_', 'TERM': 'xterm-256color', 'PS1': 'venv(base) %n@%m %1~ %# ', '_': '/Users/andresrdrgz_/Documents/PACIFICO/venv/bin/python', 'DJANGO_SETTINGS_MODULE': 'financiera.settings', 'TZ': 'UTC', 'RUN_MAIN': 'true', 'SERVER_NAME': '1.0.0.127.in-addr.arpa', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/generate_report/129/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_SEC_CH_UA': '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"', 'HTTP_SEC_CH_UA_MOBILE': '?0', 'HTTP_SEC_CH_UA_PLATFORM': '"macOS"', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7', 'HTTP_SEC_FETCH_SITE': 'same-origin', 'HTTP_SEC_FETCH_MODE': 'navigate', 'HTTP_SEC_FETCH_USER': '?1', 'HTTP_SEC_FETCH_DEST': 'document', 'HTTP_REFERER': 'http://127.0.0.1:8000/cotizacion/129/', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br, zstd', 'HTTP_ACCEPT_LANGUAGE': 'es-ES,es;q=0.9,en;q=0.8', 'HTTP_COOKIE': '********************', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x112018550>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>, 'CSRF_COOKIE': 'Gk0uqZiXrv9YPTO2H7N8lvADTSZSkvRE'}, 'request_COOKIES_items': dict_items([('localauth', 'localapif6f4b27de3df18d:'), ('isNotIncognito', 'true'), ('_ga', 'GA1.1.377595100.1724081623'), ('csrftoken', '********************'), ('sessionid', '********************')]), 'user_str': 'arodriguez', 'filtered_POST_items': [], 'settings': {'ABSOLUTE_URL_OVERRIDES': {}, 'ADMINS': [], 'ALLOWED_HOSTS': ['*'], 'APPEND_SLASH': True, 'AUTHENTICATION_BACKENDS': ['django.contrib.auth.backends.ModelBackend'], 'AUTH_PASSWORD_VALIDATORS': '********************', 'AUTH_USER_MODEL': 'auth.User', 'BASE_DIR': PosixPath('/Users/andresrdrgz_/Documents/PACIFICO/financiera'), 'CACHES': {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}, 'CACHE_MIDDLEWARE_ALIAS': 'default', 'CACHE_MIDDLEWARE_KEY_PREFIX': '********************', 'CACHE_MIDDLEWARE_SECONDS': 600, 'CSRF_COOKIE_AGE': 31449600, 'CSRF_COOKIE_DOMAIN': None, 'CSRF_COOKIE_HTTPONLY': False, 'CSRF_COOKIE_NAME': 'csrftoken', 'CSRF_COOKIE_PATH': '/', 'CSRF_COOKIE_SAMESITE': 'Lax', 'CSRF_COOKIE_SECURE': False, 'CSRF_FAILURE_VIEW': 'django.views.csrf.csrf_failure', 'CSRF_HEADER_NAME': 'HTTP_X_CSRFTOKEN', 'CSRF_TRUSTED_ORIGINS': ['https://cotfid.fpacifico.com', 'http://cotfid.fpacifico.com', 'http://localhost:8000', 'http://cotfid.fpacifico.com:8000'], 'CSRF_USE_SESSIONS': False, 'DATABASES': {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': PosixPath('/Users/andresrdrgz_/Documents/PACIFICO/financiera/db.sqlite3'), 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'CONN_MAX_AGE': 0, 'CONN_HEALTH_CHECKS': False, 'OPTIONS': {}, 'TIME_ZONE': None, 'USER': '', 'PASSWORD': '********************', 'HOST': '', 'PORT': '', 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}, 'DATABASE_ROUTERS': [], 'DATA_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'DATA_UPLOAD_MAX_NUMBER_FIELDS': 1000, 'DATA_UPLOAD_MAX_NUMBER_FILES': 100, 'DATETIME_FORMAT': 'N j, Y, P', 'DATETIME_INPUT_FORMATS': ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M'], 'DATE_FORMAT': 'N j, Y', 'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y'], 'DEBUG': True, 'DEBUG_PROPAGATE_EXCEPTIONS': False, 'DECIMAL_SEPARATOR': '.', 'DEFAULT_AUTO_FIELD': 'django.db.models.BigAutoField', 'DEFAULT_CHARSET': 'utf-8', 'DEFAULT_EXCEPTION_REPORTER': 'django.views.debug.ExceptionReporter', 'DEFAULT_EXCEPTION_REPORTER_FILTER': 'django.views.debug.SafeExceptionReporterFilter', 'DEFAULT_FROM_EMAIL': 'webmaster@localhost', 'DEFAULT_INDEX_TABLESPACE': '', 'DEFAULT_TABLESPACE': '', 'DISALLOWED_USER_AGENTS': [], 'EMAIL_BACKEND': 'django.core.mail.backends.smtp.EmailBackend', 'EMAIL_HOST': 'localhost', 'EMAIL_HOST_PASSWORD': '********************', 'EMAIL_HOST_USER': '', 'EMAIL_PORT': 25, 'EMAIL_SSL_CERTFILE': None, 'EMAIL_SSL_KEYFILE': '********************', 'EMAIL_SUBJECT_PREFIX': '[Django] ', 'EMAIL_TIMEOUT': None, 'EMAIL_USE_LOCALTIME': False, 'EMAIL_USE_SSL': False, 'EMAIL_USE_TLS': False, 'EXCEL_FILE_PATH': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/financiera/pacifico/fideicomiso/patronos.xlsx', 'FILE_UPLOAD_DIRECTORY_PERMISSIONS': None, 'FILE_UPLOAD_HANDLERS': ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler'], 'FILE_UPLOAD_MAX_MEMORY_SIZE': 2621440, 'FILE_UPLOAD_PERMISSIONS': 420, 'FILE_UPLOAD_TEMP_DIR': None, 'FIRST_DAY_OF_WEEK': 0, 'FIXTURE_DIRS': [], 'FORCE_SCRIPT_NAME': None, 'FORMAT_MODULE_PATH': None, 'FORMS_URLFIELD_ASSUME_HTTPS': False, 'FORM_RENDERER': 'django.forms.renderers.DjangoTemplates', 'IGNORABLE_404_URLS': [], 'INSTALLED_APPS': ['unfold', 'unfold.contrib.filters', 'unfold.contrib.forms', 'django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'pacifico'], 'INTERNAL_IPS': [], 'LANGUAGES': [('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], 'LANGUAGES_BIDI': ['he', 'ar', 'ar-dz', 'ckb', 'fa', 'ug', 'ur'], 'LANGUAGE_CODE': 'en-us', 'LANGUAGE_COOKIE_AGE': None, 'LANGUAGE_COOKIE_DOMAIN': None, 'LANGUAGE_COOKIE_HTTPONLY': False, 'LANGUAGE_COOKIE_NAME': 'django_language', 'LANGUAGE_COOKIE_PATH': '/', 'LANGUAGE_COOKIE_SAMESITE': None, 'LANGUAGE_COOKIE_SECURE': False, 'LOCALE_PATHS': [], 'LOGGING': {'version': 1, 'disable_existing_loggers': False, 'handlers': {'file': {'level': 'DEBUG', 'class': 'logging.FileHandler', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/debug.log'}}, 'loggers': {'django': {'handlers': ['file'], 'level': 'DEBUG', 'propagate': True}}}, 'LOGGING_CONFIG': 'logging.config.dictConfig', 'LOGIN_REDIRECT_URL': 'main_menu', 'LOGIN_URL': 'login', 'LOGOUT_REDIRECT_URL': None, 'MANAGERS': [], 'MEDIA_ROOT': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/media', 'MEDIA_URL': '/media/', 'MESSAGE_STORAGE': 'django.contrib.messages.storage.fallback.FallbackStorage', 'MIDDLEWARE': ['django.middleware.security.SecurityMiddleware', 'whitenoise.middleware.WhiteNoiseMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware'], 'MIGRATION_MODULES': {}, 'MONTH_DAY_FORMAT': 'F j', 'NUMBER_GROUPING': 0, 'PASSWORD_HASHERS': '********************', 'PASSWORD_RESET_TIMEOUT': '********************', 'PREPEND_WWW': False, 'ROOT_URLCONF': 'financiera.urls', 'SECRET_KEY': '********************', 'SECRET_KEY_FALLBACKS': '********************', 'SECURE_CONTENT_TYPE_NOSNIFF': True, 'SECURE_CROSS_ORIGIN_OPENER_POLICY': 'same-origin', 'SECURE_HSTS_INCLUDE_SUBDOMAINS': False, 'SECURE_HSTS_PRELOAD': False, 'SECURE_HSTS_SECONDS': 0, 'SECURE_PROXY_SSL_HEADER': None, 'SECURE_REDIRECT_EXEMPT': [], 'SECURE_REFERRER_POLICY': 'same-origin', 'SECURE_SSL_HOST': None, 'SECURE_SSL_REDIRECT': False, 'SERVER_EMAIL': 'root@localhost', 'SESSION_CACHE_ALIAS': 'default', 'SESSION_COOKIE_AGE': 1209600, 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_NAME': 'sessionid', 'SESSION_COOKIE_PATH': '/', 'SESSION_COOKIE_SAMESITE': 'Lax', 'SESSION_COOKIE_SECURE': False, 'SESSION_ENGINE': 'django.contrib.sessions.backends.db', 'SESSION_EXPIRE_AT_BROWSER_CLOSE': False, 'SESSION_FILE_PATH': None, 'SESSION_SAVE_EVERY_REQUEST': False, 'SESSION_SERIALIZER': 'django.contrib.sessions.serializers.JSONSerializer', 'SETTINGS_MODULE': 'financiera.settings', 'SHORT_DATETIME_FORMAT': 'm/d/Y P', 'SHORT_DATE_FORMAT': 'm/d/Y', 'SIGNING_BACKEND': 'django.core.signing.TimestampSigner', 'SILENCED_SYSTEM_CHECKS': [], 'STATICFILES_DIRS': ['/Users/andresrdrgz_/Documents/PACIFICO/financiera/static/insumos', '/Users/andresrdrgz_/Documents/PACIFICO/financiera/static/images'], 'STATICFILES_FINDERS': ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder'], 'STATICFILES_STORAGE': 'whitenoise.storage.CompressedManifestStaticFilesStorage', 'STATIC_ROOT': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/staticfiles', 'STATIC_URL': '/static/', 'STORAGES': {'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'}, 'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}}, 'TEMPLATES': [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': [], 'APP_DIRS': True, 'OPTIONS': {'context_processors': ['django.template.context_processors.debug', 'django.template.context_processors.request', 'django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages']}}], 'TEST_NON_SERIALIZED_APPS': [], 'TEST_RUNNER': 'django.test.runner.DiscoverRunner', 'THOUSAND_SEPARATOR': ',', 'TIME_FORMAT': 'P', 'TIME_INPUT_FORMATS': ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'], 'TIME_ZONE': 'UTC', 'USE_I18N': True, 'USE_THOUSAND_SEPARATOR': False, 'USE_TZ': True, 'USE_X_FORWARDED_HOST': False, 'USE_X_FORWARDED_PORT': False, 'WSGI_APPLICATION': 'financiera.wsgi.application', 'X_FRAME_OPTIONS': 'DENY', 'YEAR_MONTH_FORMAT': 'F Y'}, 'sys_executable': '/Users/andresrdrgz_/Documents/PACIFICO/venv/bin/python', 'sys_version_info': '3.11.3', 'server_time': datetime.datetime(2025, 1, 6, 15, 0, 4, 400735, tzinfo=datetime.timezone.utc), 'django_version_info': '5.1.3', 'sys_path': ['/Users/andresrdrgz_/Documents/PACIFICO/financiera', '/Users/andresrdrgz_/anaconda3/lib/python311.zip', '/Users/andresrdrgz_/anaconda3/lib/python3.11', '/Users/andresrdrgz_/anaconda3/lib/python3.11/lib-dynload', '/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages'], 'template_info': None, 'template_does_not_exist': False, 'postmortem': None, 'request_GET_items': <generator object MultiValueDict.items at 0x1120fc580>, 'request_FILES_items': <generator object MultiValueDict.items at 0x1120fcba0>, 'request_insecure_uri': 'http://127.0.0.1:8000/generate_report/129/', 'raising_view_name': 'pacifico.views.generate_report', 'exception_type': 'UnboundLocalError', 'exception_value': "cannot access local variable 'resultado' where it is not associated with a value", 'lastframe': {'exc_cause': TypeError("unsupported operand type(s) for /: 'NoneType' and 'int'"), 'exc_cause_explicit': None, 'tb': <traceback object at 0x110b9a0c0>, 'type': 'user', 'filename': '/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py', 'function': 'generate_report', 'lineno': 920, 'vars': [('request', "<WSGIRequest: GET '/generate_report/129/'>"), ('numero_cotizacion', '129'), ('cotizacion', '<Cotizacion: 129 - asd - asd>'), ('error_message', '"unsupported operand type(s) for /: \'NoneType\' and \'int\'"')], 'id': 4575568064, 'pre_context': ["            response = HttpResponse(f.read(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')", "            response['Content-Disposition'] = f'attachment; filename={filename}'", '            return response', '    ', '    except Exception as e:', '        error_message = str(e)', '        log_error(error_message, request.user.username)'], 'context_line': "        return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)", 'post_context': ['        ', '', '@login_required', 'def main_menu(request):', "    return render(request, 'main_menu.html')", ''], 'pre_context_lineno': 913, 'colno': '\n                                                                                     ^^^^^^^^^', 'tb_area_colno': '\n                                                                            ^^^^^^^^^'}}]
ERROR:django.request:Internal Server Error: /generate_report/129/
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py", line 534, in generate_report
    'apcPI': cotizacion.apcPI / 100,
             ~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py", line 920, in generate_report
    return JsonResponse({'status': 'error', 'message': str(e), 'resultado': resultado}, status=500)
                                                                            ^^^^^^^^^
UnboundLocalError: cannot access local variable 'resultado' where it is not associated with a value
ERROR:django.server:"GET /generate_report/129/ HTTP/1.1" 500 76262
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py previous mtime: 1736175186.7841218, current mtime: 1736175753.6772125
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py notified as changed. Signal results: [(<function template_changed at 0x10639cf40>, None), (<function translation_file_changed at 0x106e6dbc0>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py changed, reloading.
