ERROR:root:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
DEBUG:django.db.backends:(0.000) SELECT "pacifico_aseguradora"."id", "pacifico_aseguradora"."descripcion", "pacifico_aseguradora"."codigo" FROM "pacifico_aseguradora"; args=(); alias=default
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('14531.14'), 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.10'), 'calcComiCierreFinal': Decimal('15.06'), 'auxPlazoPago': 72, 'wrkLetraSinSeguros': Decimal('271.08'), 'wrkLetraSeguro': Decimal('11.44'), 'wrkMontoLetra': Decimal('282.52'), 'montoMensualSeguro': Decimal('28.36'), 'wrkLetraConSeguros': Decimal('310.88'), 'tablaTotalPagos': Decimal('20341.44'), 'nombreCliente': 'asdj', 'valorAuto': Decimal('12341.00'), 'abono': Decimal('0.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-310.88'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-310.88'), 'porSalarioNetoCompleto': Decimal('0.00'), 'numero_cotizacion': 109}
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('14531.14'), 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.10'), 'calcComiCierreFinal': Decimal('15.06'), 'auxPlazoPago': 72, 'wrkLetraSinSeguros': Decimal('271.08'), 'wrkLetraSeguro': Decimal('11.44'), 'wrkMontoLetra': Decimal('282.52'), 'montoMensualSeguro': Decimal('28.36'), 'wrkLetraConSeguros': Decimal('310.88'), 'tablaTotalPagos': Decimal('20341.44'), 'nombreCliente': 'asdj', 'valorAuto': Decimal('12341.00'), 'abono': Decimal('0.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-310.88'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-310.88'), 'porSalarioNetoCompleto': Decimal('0.00'), 'numero_cotizacion': 109}
DEBUG:django.db.backends:(0.000) BEGIN; args=None; alias=default
DEBUG:django.db.backends:(0.001) UPDATE "django_session" SET "session_data" = '.eJyFVltvozoQ_isRzy3imkDfKElX6KRJ1CR9OlJkjJO6CxjZJmfPrva_79gQLj1B582ey-eZz-Px_DJOqJYfp1oQfqKZ8WQ4xsNQliL8nZRKkX2i8sJMzErJaWoqE7PVCvOVZSR_bm1HAB9IfIC3hQMHpcjNSIYIti3HOVs-Sa00zQLf85xwYYUkRSnJsB8GqbcA5cIP3bmfpj4OLADlRNS5RBkznn4ZAANBOcGDIWpcc4FyOMR2wUyQH2BhvEb7-LhONlsQfdYpzbWjofeYyVdIg-0AUqIC5LbjerZpgQrl-IAESkpJQGs8WaYV2o08ZgWNKeGcKLHtPhio_rHL0U-2QxcAWTgPRoUkZyVsnEZLOGWY6mAB5cx4gU6VtvZUHBm9sD251BwEkMuZ4A8Uw1F1roJ1LMd_tOxHy1PpnzIiCMqQPlx7F1RQVr4D5yRjXMcKGLREJaboBntGuSAPRgHO4uWLDswLRQQqa5TfhK5nmc6i1bySUgx0TmC6c8VGKVXOYgB0QUKyF5oRqgNTxqFthprtF5VXUlJMW6ra1JwmNUWuNtlxVpD4r0Hq9qLV6wvbMIk4BQZsc-E38g2RLIakSI4AvdShjC9LJQ3VYfumBaFLuNxnXktNowKBW9LYDph4vmtrbv_h37VwTSRHKm3H9J0bJagkn-wAUjsAOsJBfAdapLpqbM8E6EJbnvyKcaxrzLQBREISHaEBCFV9Cb2PMkWRDtdSoaY5OihrzTUcaKkq9byh6itQrwFGKZRZ6KpQenFX2Z4XOmYQDnU6iRhVVGrGhnRoJm6H2U0UAzqeQbjwAzNY9G9oBeUs6VVd19yc-xAFtzU1VnMNKyFpoQs6NCFydobk9TtO9sl-9hy9vSUR3H7JFKlxTglEDloksk9VFCSrczQQZwKkklZsyXBdgFTVWbxaHtcKBVV4j5l6usZjs90lmuUryhmPajnqAkx-edfX7pEZ9uxxtk82s_fVZrlabt8MddEcowbD2CT7fbQBYU5LchO-vG03h2SlbP8lqD0OahxIrKDm2a5Oc9r2CV_Rw1EpmucN3tHxsH39u7YsbB-SWHWwsiZX1mIr7WxzXL0rxXeawxMC90_SqAGMpdCIr_p5qHs3NE2kqKDz8KsquJYTWl6gMFSh6W3D-6qoQAh3ZOyib9vZ-3Z93Byit2SrWDjGx7d9tF7tZ-tVBJx80236DPWluoyIdnGLhRGHqkPtDlLVBrDdJ7CvmKDN49XqivAzzY8lvRIuqHrxtwihzavdMxKkbUxt0_tgHInVD8hb6BrWeQ-ESyz7VlhxKLubmfLWgpFJCj1cDE20YGTCoNGPTLRgZCIowqjqA2r2X2JBqDdQu5E6o3zbnWNrm5vIbjm57ZWffd_RGTk6dxyd-47uyNG94-jed_RGjt4dR6-nAB7ZO8vrUt-03RToWDhIf6wYJz3WOZNIzgSSM4HkTiK5E0juBJI3ieRNIE3x5E8i-RNI_gTSfBJpPoE0H04VVuMOK7tbOd3K7VZet_K71bxbLbpV0K3CHnlwyK1A4M0S_to3tArGOcY5koQ1ou7TomXzb6kfdAH9Peh1Met1rm2ZQdD-aoPvLoLRFuYdPT9azYwoPtTk225Rqge-fr2D7x6-H2jBrbRtW2pUMZ4eb-fAVLAfKsaGEZZ9e5PNx920525IaMfTL-q2MY6VSyJwrb7EJeUEt6fJ22jR324v7zzEmlz-9yyYtqqcdK3wPsIXo_8kO63vNRPsDVzV5wiVwU7widOf7VAIP_vv338AbyM2rw:1tU5tU:HFgC409ptNGrAmZVgo9psWsivS6P9N0uH4udaBsFgwg', "expire_date" = '2025-01-18 15:16:52.531269' WHERE "django_session"."session_key" = 's3o72ng3j5dmlqagdhvjnkyz0bxfikg3'; args=('.eJyFVltvozoQ_isRzy3imkDfKElX6KRJ1CR9OlJkjJO6CxjZJmfPrva_79gQLj1B582ey-eZz-Px_DJOqJYfp1oQfqKZ8WQ4xsNQliL8nZRKkX2i8sJMzErJaWoqE7PVCvOVZSR_bm1HAB9IfIC3hQMHpcjNSIYIti3HOVs-Sa00zQLf85xwYYUkRSnJsB8GqbcA5cIP3bmfpj4OLADlRNS5RBkznn4ZAANBOcGDIWpcc4FyOMR2wUyQH2BhvEb7-LhONlsQfdYpzbWjofeYyVdIg-0AUqIC5LbjerZpgQrl-IAESkpJQGs8WaYV2o08ZgWNKeGcKLHtPhio_rHL0U-2QxcAWTgPRoUkZyVsnEZLOGWY6mAB5cx4gU6VtvZUHBm9sD251BwEkMuZ4A8Uw1F1roJ1LMd_tOxHy1PpnzIiCMqQPlx7F1RQVr4D5yRjXMcKGLREJaboBntGuSAPRgHO4uWLDswLRQQqa5TfhK5nmc6i1bySUgx0TmC6c8VGKVXOYgB0QUKyF5oRqgNTxqFthprtF5VXUlJMW6ra1JwmNUWuNtlxVpD4r0Hq9qLV6wvbMIk4BQZsc-E38g2RLIakSI4AvdShjC9LJQ3VYfumBaFLuNxnXktNowKBW9LYDph4vmtrbv_h37VwTSRHKm3H9J0bJagkn-wAUjsAOsJBfAdapLpqbM8E6EJbnvyKcaxrzLQBREISHaEBCFV9Cb2PMkWRDtdSoaY5OihrzTUcaKkq9byh6itQrwFGKZRZ6KpQenFX2Z4XOmYQDnU6iRhVVGrGhnRoJm6H2U0UAzqeQbjwAzNY9G9oBeUs6VVd19yc-xAFtzU1VnMNKyFpoQs6NCFydobk9TtO9sl-9hy9vSUR3H7JFKlxTglEDloksk9VFCSrczQQZwKkklZsyXBdgFTVWbxaHtcKBVV4j5l6usZjs90lmuUryhmPajnqAkx-edfX7pEZ9uxxtk82s_fVZrlabt8MddEcowbD2CT7fbQBYU5LchO-vG03h2SlbP8lqD0OahxIrKDm2a5Oc9r2CV_Rw1EpmucN3tHxsH39u7YsbB-SWHWwsiZX1mIr7WxzXL0rxXeawxMC90_SqAGMpdCIr_p5qHs3NE2kqKDz8KsquJYTWl6gMFSh6W3D-6qoQAh3ZOyib9vZ-3Z93Byit2SrWDjGx7d9tF7tZ-tVBJx80236DPWluoyIdnGLhRGHqkPtDlLVBrDdJ7CvmKDN49XqivAzzY8lvRIuqHrxtwihzavdMxKkbUxt0_tgHInVD8hb6BrWeQ-ESyz7VlhxKLubmfLWgpFJCj1cDE20YGTCoNGPTLRgZCIowqjqA2r2X2JBqDdQu5E6o3zbnWNrm5vIbjm57ZWffd_RGTk6dxyd-47uyNG94-jed_RGjt4dR6-nAB7ZO8vrUt-03RToWDhIf6wYJz3WOZNIzgSSM4HkTiK5E0juBJI3ieRNIE3x5E8i-RNI_gTSfBJpPoE0H04VVuMOK7tbOd3K7VZet_K71bxbLbpV0K3CHnlwyK1A4M0S_to3tArGOcY5koQ1ou7TomXzb6kfdAH9Peh1Met1rm2ZQdD-aoPvLoLRFuYdPT9azYwoPtTk225Rqge-fr2D7x6-H2jBrbRtW2pUMZ4eb-fAVLAfKsaGEZZ9e5PNx920525IaMfTL-q2MY6VSyJwrb7EJeUEt6fJ22jR324v7zzEmlz-9yyYtqqcdK3wPsIXo_8kO63vNRPsDVzV5wiVwU7widOf7VAIP_vv338AbyM2rw:1tU5tU:HFgC409ptNGrAmZVgo9psWsivS6P9N0uH4udaBsFgwg', '2025-01-18 15:16:52.531269', 's3o72ng3j5dmlqagdhvjnkyz0bxfikg3'); alias=default
DEBUG:django.db.backends:(0.000) COMMIT; args=None; alias=default
INFO:django.server:"POST /cotizacion/109/ HTTP/1.1" 200 151410
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1732569332.5017526
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/session.py first seen with mtime 1732569332.5019946
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/anaconda3/lib/python3.11/_strptime.py first seen with mtime 1681948558.9095042
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/__init__.py first seen with mtime 1732569332.0690286
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1732569332.5018916
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/formats.py first seen with mtime 1732569332.0692546
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/sessions/serializers.py first seen with mtime 1732569332.5685349
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context_processors.py first seen with mtime 1732569332.7133355
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/context_processors.py first seen with mtime 1732569332.2745264
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/context_processors.py first seen with mtime 1732569332.500866
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py previous mtime: 1736003808.9978824, current mtime: 1736003898.7623634
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py notified as changed. Signal results: [(<function template_changed at 0x106768f40>, None), (<function translation_file_changed at 0x106fc1bc0>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py changed, reloading.
