ERROR:root:name 'generarFideicomiso4' is not defined
DEBUG:django.db.backends:(0.000) SELECT "pacifico_aseguradora"."id", "pacifico_aseguradora"."descripcion", "pacifico_aseguradora"."codigo" FROM "pacifico_aseguradora"; args=(); alias=default
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('18799.39'), 'numero_cotizacion': 64, 'r1': Decimal('15.00'), 'tasaEstimada': Decimal('11.49'), 'calcComiCierreFinal': Decimal('14.58'), 'auxPlazoPago': 96, 'wrkLetraSinSeguros': Decimal('312.24'), 'wrkLetraSeguro': Decimal('14.80'), 'wrkMontoLetra': Decimal('327.04'), 'montoMensualSeguro': Decimal('26.56'), 'wrkLetraConSeguros': Decimal('353.60'), 'tablaTotalPagos': Decimal('31395.84'), 'nombreCliente': 'ROGER ABDIEL SAMUDIO RUIX', 'valorAuto': Decimal('18796.48'), 'abono': Decimal('2819.47'), 'salarioBaseMensual': Decimal('880.00'), 'totalDescuentosLegales': Decimal('101.88'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('778.12'), 'salarioNeto': Decimal('424.52'), 'porSalarioNeto': Decimal('48.24'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('880.00'), 'totalDescuentosLegalesCompleto': Decimal('101.88'), 'salarioNetoActualCompleto': Decimal('778.12'), 'salarioNetoCompleto': Decimal('424.52'), 'porSalarioNetoCompleto': Decimal('48.24'), 'cosalarioBaseMensual': None, 'cototalDescuentosLegales': None, 'cototalDescuentoDirecto': None, 'cototalPagoVoluntario': None, 'cosalarioNetoActual': None, 'cosalarioNeto': None, 'coporSalarioNeto': None, 'cototalIngresosAdicionales': Decimal('0.00'), 'cototalIngresosMensualesCompleto': None, 'cototalDescuentosLegalesCompleto': None, 'cosalarioNetoActualCompleto': None, 'cosalarioNetoCompleto': None, 'coporSalarioNetoCompleto': None, 'porcentajeLetraSeguro': Decimal('40.18'), 'coporcentajeLetraSeguro': 0, 'porcentajeLetraSeguroCompleto': Decimal('40.18'), 'coporcentajeLetraSeguroCompleto': 0, 'familiarSalarioBaseMensual': Decimal('778.12'), 'familiarSalarioNeto': Decimal('424.52'), 'familiarporNetoActual': Decimal('88.42'), 'familiarpoSalarioNeto': Decimal('48.24'), 'familiarNetoActualCompleto': Decimal('778.12'), 'familiarporNetoActualCompleto': 0, 'familiarSalarioNetoCompleto': Decimal('424.52'), 'familiarporSalarioNeto': Decimal('48.24')}
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('18799.39'), 'numero_cotizacion': 64, 'r1': Decimal('15.00'), 'tasaEstimada': Decimal('11.49'), 'calcComiCierreFinal': Decimal('14.58'), 'auxPlazoPago': 96, 'wrkLetraSinSeguros': Decimal('312.24'), 'wrkLetraSeguro': Decimal('14.80'), 'wrkMontoLetra': Decimal('327.04'), 'montoMensualSeguro': Decimal('26.56'), 'wrkLetraConSeguros': Decimal('353.60'), 'tablaTotalPagos': Decimal('31395.84'), 'nombreCliente': 'ROGER ABDIEL SAMUDIO RUIX', 'valorAuto': Decimal('18796.48'), 'abono': Decimal('2819.47'), 'salarioBaseMensual': Decimal('880.00'), 'totalDescuentosLegales': Decimal('101.88'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('778.12'), 'salarioNeto': Decimal('424.52'), 'porSalarioNeto': Decimal('48.24'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('880.00'), 'totalDescuentosLegalesCompleto': Decimal('101.88'), 'salarioNetoActualCompleto': Decimal('778.12'), 'salarioNetoCompleto': Decimal('424.52'), 'porSalarioNetoCompleto': Decimal('48.24'), 'cosalarioBaseMensual': None, 'cototalDescuentosLegales': None, 'cototalDescuentoDirecto': None, 'cototalPagoVoluntario': None, 'cosalarioNetoActual': None, 'cosalarioNeto': None, 'coporSalarioNeto': None, 'cototalIngresosAdicionales': Decimal('0.00'), 'cototalIngresosMensualesCompleto': None, 'cototalDescuentosLegalesCompleto': None, 'cosalarioNetoActualCompleto': None, 'cosalarioNetoCompleto': None, 'coporSalarioNetoCompleto': None, 'porcentajeLetraSeguro': Decimal('40.18'), 'coporcentajeLetraSeguro': 0, 'porcentajeLetraSeguroCompleto': Decimal('40.18'), 'coporcentajeLetraSeguroCompleto': 0, 'familiarSalarioBaseMensual': Decimal('778.12'), 'familiarSalarioNeto': Decimal('424.52'), 'familiarporNetoActual': Decimal('88.42'), 'familiarpoSalarioNeto': Decimal('48.24'), 'familiarNetoActualCompleto': Decimal('778.12'), 'familiarporNetoActualCompleto': 0, 'familiarSalarioNetoCompleto': Decimal('424.52'), 'familiarporSalarioNeto': Decimal('48.24')}
INFO:django.server:"POST /cotizacion/64/ HTTP/1.1" 200 201257
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/context_processors.py first seen with mtime 1732569332.500866
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/context_processors.py first seen with mtime 1732569332.2745264
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/__init__.py first seen with mtime 1732569332.0690286
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/formats.py first seen with mtime 1732569332.0692546
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/anaconda3/lib/python3.11/_strptime.py first seen with mtime 1681948558.9095042
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context_processors.py first seen with mtime 1732569332.7133355
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/session.py first seen with mtime 1732569332.5019946
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1732569332.5018916
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1732569332.5017526
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/sessions/serializers.py first seen with mtime 1732569332.5685349
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/viewsFideicomiso/cotizadorFideicomiso.py previous mtime: 1738178802.7768273, current mtime: 1738178817.36346
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/viewsFideicomiso/cotizadorFideicomiso.py notified as changed. Signal results: [(<function template_changed at 0x103e64f40>, None), (<function translation_file_changed at 0x1046bdc60>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/viewsFideicomiso/cotizadorFideicomiso.py changed, reloading.
