ERROR:root:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
DEBUG:django.db.backends:(0.000) SELECT "pacifico_aseguradora"."id", "pacifico_aseguradora"."descripcion", "pacifico_aseguradora"."codigo" FROM "pacifico_aseguradora"; args=(); alias=default
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('14531.14'), 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.10'), 'calcComiCierreFinal': Decimal('15.06'), 'auxPlazoPago': 72, 'wrkLetraSinSeguros': Decimal('271.08'), 'wrkLetraSeguro': Decimal('11.44'), 'wrkMontoLetra': Decimal('282.52'), 'montoMensualSeguro': Decimal('28.36'), 'wrkLetraConSeguros': Decimal('310.88'), 'tablaTotalPagos': Decimal('20341.44'), 'nombreCliente': 'asdj', 'valorAuto': Decimal('12341.00'), 'abono': Decimal('0.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-310.88'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-310.88'), 'porSalarioNetoCompleto': Decimal('0.00'), 'numero_cotizacion': 109}
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('14531.14'), 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.10'), 'calcComiCierreFinal': Decimal('15.06'), 'auxPlazoPago': 72, 'wrkLetraSinSeguros': Decimal('271.08'), 'wrkLetraSeguro': Decimal('11.44'), 'wrkMontoLetra': Decimal('282.52'), 'montoMensualSeguro': Decimal('28.36'), 'wrkLetraConSeguros': Decimal('310.88'), 'tablaTotalPagos': Decimal('20341.44'), 'nombreCliente': 'asdj', 'valorAuto': Decimal('12341.00'), 'abono': Decimal('0.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-310.88'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-310.88'), 'porSalarioNetoCompleto': Decimal('0.00'), 'numero_cotizacion': 109}
DEBUG:django.db.backends:(0.000) BEGIN; args=None; alias=default
DEBUG:django.db.backends:(0.000) UPDATE "django_session" SET "session_data" = '.eJyFVltvozoQ_isRzy3CXBLoGyXpCp00iZqkT0eKDDipu4CRbXL27Gr_-44N4dITdN7suXye-Twezy_jhGv5caoF4SeaGU-GbTwMZQlOv5NSKbJPXF6YmbJScpqYysRstcJ8ZRnJn1vbEcAHFh_gbaW-jRPsZCTDJEWWbZ8tjyRWkmS-57p2sLACkuCEZKkX-Im7AOXCC5y5lyRe6lsAyomoc4kzZjz9MgAGgrL9B0PUac0FzuEQ5ICZID_AwngN99FxHW-2IPqsE5prR0PvUyZfIQ22A0iJC5Aj23GRaYEK5-kBCxyXkoDWeLJMK0CNPGIFjSjhnCgxch4MXP_Y5fgn2-ELgCzsB6PCkrMSNnajJZyylOpgAeXMeIFPlbZ2VRwZvbA9udQcBJDLmaQfOIKj6lwFa1u292ihR8tV6Z8yIgjOsD5cexdUUFa-A-ckY1zHChi0xGVK8Q32jHNBHowCnMXLFx2YF4oIXNY4vwkd1zLtRat5JaUY6GzfdOaKjVKqnMUA6IKFZC80I1QHpowDZAaa7ReVV1zSlLZUtanZTWqKXG2y46wg0V-D1NGi1esL2zCJOQUGkLnwGvmGSBZBUiTHgF7qUMaXpZKG6kCeaUHoEi73mddS06hA4JY0tg0mrucgze0__LsWronkWKVtm559owSX5JMdQIp8oCMYxHegRaKrBrkmQBfa8uRVjKe6xkwEIBKS6Aj1QajqS-h9mCmKdLiWCjXJ8UFZa67hQEtVqesOVV-Beg0wSqHMAkeF0ou7ynbdwDb9YKjTSUS4olIzNqRDM3E7DDVRDOh4BuHC801_0b-hFZSzpFd1XXNz7kEUHGlqrOYaVkLSQhd0YELk7AzJ63cc7-P97Dl8e4tDuP2SKVKjnBKIHLRYZJ-qKEhW53ggzgRIJa3YkqV1AVJVZ9FqeVwrFFyl-5Spp2s8NttdrFm-4pzxsJajLsDkl3d97R6ZgWaPs328mb2vNsvVcvtmqIvmKW4wjE2834cbEOa0JDfhy9t2c4hXyvZfgtvjoMaBxApqnu3qJKdtn_AUPRyXonne4B0eD9vXv2vLStEhjlQHK2tyZS220s42x9W7UnynOTwhcP8kjRrAWAKN-Kqfh7p3Q9NEigo6D7-qgms5oeUFCkMVmt42vK-KCoRwR8Yu_LadvW_Xx80hfIu3ioVjdHzbh-vVfrZehcDJN92mz1BfqsuIcBe1WCnmUHW43UGq2gC2-xj2FRO0ebxaXRF-pvmxpFfCBVUv_hYhtHm1e8aCtI2pbXofjGOx-gF5C13DOu-BcJnKvhVWHMruZqa8tWBkkkAPF0MTLRiZMGj0IxMtGJkIilNc9QE1-y-xYNwbqN1InVG-7c5B2uYmQi0nt73yQ_cd7ZGjfcfRvu_ojBydO47OfUd35OjecXR7CuCRvbO8LvVNo6ZAx8JB-mPFOOmxzp5EsieQ7AkkZxLJmUByJpDcSSR3AmmKJ28SyZtA8iaQ5pNI8wmk-XCqsBp3WKFuZXcrp1u53crrVvNutehWfrcKeuTBIbcCgTdL-Gvf0CoY5xjnWBLWiLpPi5bNv6V-0AX0d7_XRazXOcgyfb_91QbfXQijLcw7en60mhlRfKjJt93iRA98_XoH3z18P9CCW2nbttSoYjw93s6BqWA_VIwNw1T27U02H3fTnrshoR1Pv6jbxjhWLolIa_UlLiknaXuavI0W_e328s5DrMnlf8-CaavKSdcK7yN8MfpPstP6XjPB3sBVfY5QGewEnzj92Q6FyEa_f_8Bbx02rQ:1tU5sL:433h1WFMNjSBGt5n8JZ1ReqVzi3CCTbPD-GzFG6N3ao', "expire_date" = '2025-01-18 15:15:41.327316' WHERE "django_session"."session_key" = 's3o72ng3j5dmlqagdhvjnkyz0bxfikg3'; args=('.eJyFVltvozoQ_isRzy3CXBLoGyXpCp00iZqkT0eKDDipu4CRbXL27Gr_-44N4dITdN7suXye-Twezy_jhGv5caoF4SeaGU-GbTwMZQlOv5NSKbJPXF6YmbJScpqYysRstcJ8ZRnJn1vbEcAHFh_gbaW-jRPsZCTDJEWWbZ8tjyRWkmS-57p2sLACkuCEZKkX-Im7AOXCC5y5lyRe6lsAyomoc4kzZjz9MgAGgrL9B0PUac0FzuEQ5ICZID_AwngN99FxHW-2IPqsE5prR0PvUyZfIQ22A0iJC5Aj23GRaYEK5-kBCxyXkoDWeLJMK0CNPGIFjSjhnCgxch4MXP_Y5fgn2-ELgCzsB6PCkrMSNnajJZyylOpgAeXMeIFPlbZ2VRwZvbA9udQcBJDLmaQfOIKj6lwFa1u292ihR8tV6Z8yIgjOsD5cexdUUFa-A-ckY1zHChi0xGVK8Q32jHNBHowCnMXLFx2YF4oIXNY4vwkd1zLtRat5JaUY6GzfdOaKjVKqnMUA6IKFZC80I1QHpowDZAaa7ReVV1zSlLZUtanZTWqKXG2y46wg0V-D1NGi1esL2zCJOQUGkLnwGvmGSBZBUiTHgF7qUMaXpZKG6kCeaUHoEi73mddS06hA4JY0tg0mrucgze0__LsWronkWKVtm559owSX5JMdQIp8oCMYxHegRaKrBrkmQBfa8uRVjKe6xkwEIBKS6Aj1QajqS-h9mCmKdLiWCjXJ8UFZa67hQEtVqesOVV-Beg0wSqHMAkeF0ou7ynbdwDb9YKjTSUS4olIzNqRDM3E7DDVRDOh4BuHC801_0b-hFZSzpFd1XXNz7kEUHGlqrOYaVkLSQhd0YELk7AzJ63cc7-P97Dl8e4tDuP2SKVKjnBKIHLRYZJ-qKEhW53ggzgRIJa3YkqV1AVJVZ9FqeVwrFFyl-5Spp2s8NttdrFm-4pzxsJajLsDkl3d97R6ZgWaPs328mb2vNsvVcvtmqIvmKW4wjE2834cbEOa0JDfhy9t2c4hXyvZfgtvjoMaBxApqnu3qJKdtn_AUPRyXonne4B0eD9vXv2vLStEhjlQHK2tyZS220s42x9W7UnynOTwhcP8kjRrAWAKN-Kqfh7p3Q9NEigo6D7-qgms5oeUFCkMVmt42vK-KCoRwR8Yu_LadvW_Xx80hfIu3ioVjdHzbh-vVfrZehcDJN92mz1BfqsuIcBe1WCnmUHW43UGq2gC2-xj2FRO0ebxaXRF-pvmxpFfCBVUv_hYhtHm1e8aCtI2pbXofjGOx-gF5C13DOu-BcJnKvhVWHMruZqa8tWBkkkAPF0MTLRiZMGj0IxMtGJkIilNc9QE1-y-xYNwbqN1InVG-7c5B2uYmQi0nt73yQ_cd7ZGjfcfRvu_ojBydO47OfUd35OjecXR7CuCRvbO8LvVNo6ZAx8JB-mPFOOmxzp5EsieQ7AkkZxLJmUByJpDcSSR3AmmKJ28SyZtA8iaQ5pNI8wmk-XCqsBp3WKFuZXcrp1u53crrVvNutehWfrcKeuTBIbcCgTdL-Gvf0CoY5xjnWBLWiLpPi5bNv6V-0AX0d7_XRazXOcgyfb_91QbfXQijLcw7en60mhlRfKjJt93iRA98_XoH3z18P9CCW2nbttSoYjw93s6BqWA_VIwNw1T27U02H3fTnrshoR1Pv6jbxjhWLolIa_UlLiknaXuavI0W_e328s5DrMnlf8-CaavKSdcK7yN8MfpPstP6XjPB3sBVfY5QGewEnzj92Q6FyEa_f_8Bbx02rQ:1tU5sL:433h1WFMNjSBGt5n8JZ1ReqVzi3CCTbPD-GzFG6N3ao', '2025-01-18 15:15:41.327316', 's3o72ng3j5dmlqagdhvjnkyz0bxfikg3'); alias=default
DEBUG:django.db.backends:(0.000) COMMIT; args=None; alias=default
INFO:django.server:"POST /cotizacion/109/ HTTP/1.1" 200 151410
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/sessions/serializers.py first seen with mtime 1732569332.5685349
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/session.py first seen with mtime 1732569332.5019946
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/context_processors.py first seen with mtime 1732569332.500866
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1732569332.5017526
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/context_processors.py first seen with mtime 1732569332.2745264
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/anaconda3/lib/python3.11/_strptime.py first seen with mtime 1681948558.9095042
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1732569332.5018916
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/__init__.py first seen with mtime 1732569332.0690286
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/formats.py first seen with mtime 1732569332.0692546
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context_processors.py first seen with mtime 1732569332.7133355
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py previous mtime: 1736003736.612672, current mtime: 1736003775.8643882
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py notified as changed. Signal results: [(<function template_changed at 0x103754f40>, None), (<function translation_file_changed at 0x10426dbc0>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py changed, reloading.
