ERROR:root:int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
DEBUG:django.db.backends:(0.000) SELECT "pacifico_aseguradora"."id", "pacifico_aseguradora"."descripcion", "pacifico_aseguradora"."codigo" FROM "pacifico_aseguradora"; args=(); alias=default
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('14531.14'), 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.10'), 'calcComiCierreFinal': Decimal('15.06'), 'auxPlazoPago': 72, 'wrkLetraSinSeguros': Decimal('271.08'), 'wrkLetraSeguro': Decimal('11.44'), 'wrkMontoLetra': Decimal('282.52'), 'montoMensualSeguro': Decimal('28.36'), 'wrkLetraConSeguros': Decimal('310.88'), 'tablaTotalPagos': Decimal('20341.44'), 'nombreCliente': 'asdj', 'valorAuto': Decimal('12341.00'), 'abono': Decimal('0.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-310.88'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-310.88'), 'porSalarioNetoCompleto': Decimal('0.00'), 'numero_cotizacion': 109}
DEBUG:django.template:Exception while resolving variable 'lineaAuto' in template 'fideicomiso_form.html'.
Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 899, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'lineaAuto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/base.py", line 906, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [lineaAuto] in {'auxMonto2': Decimal('14531.14'), 'r1': Decimal('14.00'), 'tasaEstimada': Decimal('9.10'), 'calcComiCierreFinal': Decimal('15.06'), 'auxPlazoPago': 72, 'wrkLetraSinSeguros': Decimal('271.08'), 'wrkLetraSeguro': Decimal('11.44'), 'wrkMontoLetra': Decimal('282.52'), 'montoMensualSeguro': Decimal('28.36'), 'wrkLetraConSeguros': Decimal('310.88'), 'tablaTotalPagos': Decimal('20341.44'), 'nombreCliente': 'asdj', 'valorAuto': Decimal('12341.00'), 'abono': Decimal('0.00'), 'salarioBaseMensual': Decimal('0.00'), 'totalDescuentosLegales': Decimal('0.00'), 'totalDescuentoDirecto': Decimal('0.00'), 'totalPagoVoluntario': Decimal('0.00'), 'salarioNetoActual': Decimal('0.00'), 'salarioNeto': Decimal('-310.88'), 'porSalarioNeto': Decimal('0.00'), 'totalIngresosAdicionales': Decimal('0.00'), 'totalIngresosMensualesCompleto': Decimal('0.00'), 'totalDescuentosLegalesCompleto': Decimal('0.00'), 'salarioNetoActualCompleto': Decimal('0.00'), 'salarioNetoCompleto': Decimal('-310.88'), 'porSalarioNetoCompleto': Decimal('0.00'), 'numero_cotizacion': 109}
DEBUG:django.db.backends:(0.000) BEGIN; args=None; alias=default
DEBUG:django.db.backends:(0.000) UPDATE "django_session" SET "session_data" = '.eJyFVltvozoQ_isRzy0CAwn0jZJ0hU6aRE3SpyNFBpzUXcDINjl7drX_fceGcOkJOm_2XD7PfB6P55dxwrX8ONWC8BPNjCcDGQ9DWYLT76RUiuwTlxdmpqyUnCamMjFbrTBfWUby59Z2BPCBxQd4W6mPcIKdjGSYpLaF0NnySGIlSeZ7rouChRWQBCckS73AT9wFKBde4My9JPFS3wJQTkSdS5wx4-mXATAQFPIfDFGnNRc4h0NsB8wE-QEWxmu4j47reLMF0Wed0Fw7GnqfMvkKabAdQEpcgNxGjmubFqhwnh6wwHEpCWiNJ8u0AruRR6ygESWcEyW2nQcD1z92Of7JdvgCIAv0YFRYclbCBjVawilLqQ4WUM6MF_hUaWtXxZHRC9uTS81BALmcSfqBIziqzlWwyELeo2U_Wq5K_5QRQXCG9eHau6CCsvIdOCcZ4zpWwKAlLlOKb7BnnAvyYBTgLF6-6MC8UETgssb5Tei4lokWreaVlGKgQ77pzBUbpVQ5iwHQBQvJXmhGqA5MGQe2GWi2X1RecUlT2lLVpoaa1BS52mTHWUGivwap24tWry9swyTmFBiwzYXXyDdEsgiSIjkG9FKHMr4slTRUh-2ZFoQu4XKfeS01jQoEbkljIzBxPcfW3P7Dv2vhmkiOVdrI9NCNElyST3YAqe0DHcEgvgMtEl01tmsCdKEtT17FeKprzLQBREISHaE-CFV9Cb0PM0WRDtdSoSY5PihrzTUcaKkqdd2h6itQrwFGKZRZ4KhQenFX2a4bINMPhjqdRIQrKjVjQzo0E7fD7CaKAR3PIFx4vukv-je0gnKW9Kqua27OPYiC25oaq7mGlZC00AUdmBA5O0Py-h3H-3g_ew7f3uIQbr9kitQopwQiBy0W2acqCpLVOR6IMwFSSSu2ZGldgFTVWbRaHtcKBVfpPmXq6RqPzXYXa5avOGc8rOWoCzD55V1fu0dm2LPH2T7ezN5Xm-VquX0z1EXzFDcYxibe78MNCHNakpvw5W27OcQrZfsvwe1xUONAYgU1z3Z1ktO2T3iKHo5L0Txv8A6Ph-3r37VlpfYhjlQHK2tyZS220s42x9W7UnynOTwhcP8kjRrAWAKN-Kqfh7p3Q9NEigo6D7-qgms5oeUFCkMVmt42vK-KCoRwR8Yu_LadvW_Xx80hfIu3ioVjdHzbh-vVfrZehcDJN92mz1BfqsuIcBe1WCnmUHW43UGq2gC2-xj2FRO0ebxaXRF-pvmxpFfCBVUv_hYhtHm1e8aCtI2pbXofjGOx-gF5C13DOu-BcJnKvhVWHMruZqa8tWBkkkAPF0MTLRiZMGj0IxMtGJkIilNc9QE1-y-xYNwbqN1InVG-7c6xtc1NZLec3PbKz77viEaO6I4juu_ojBydO47OfUd35OjecXR7CuCRvbO8LvVN202BjoWD9MeKcdJjHZpEQhNIaALJmURyJpCcCSR3EsmdQJriyZtE8iaQvAmk-STSfAJpPpwqrMYdVna3Qt3K6VZut_K61bxbLbqV362CHnlwyK1A4M0S_to3tArGOcY5loQ1ou7TomXzb6kfdAH93e91Eet1jm2Zvt_-aoPvLoTRFuYdPT9azYwoPtTk225xoge-fr2D7x6-H2jBrbRtW2pUMZ4eb-fAVLAfKsaGYSr79iabj7tpz92Q0I6nX9RtYxwrl0SktfoSl5STtD1N3kaL_nZ7eech1uTyv2fBtFXlpGuF9xG-GP0n2Wl9r5lgb-CqPkeoDHaCT5z-bIdCG6Hfv_8AbyA2rg:1tU5sx:1gQXTzgVSrBSNqzteSiYcKgNNzxzIwUTj2cDQjFzvHs', "expire_date" = '2025-01-18 15:16:19.794329' WHERE "django_session"."session_key" = 's3o72ng3j5dmlqagdhvjnkyz0bxfikg3'; args=('.eJyFVltvozoQ_isRzy0CAwn0jZJ0hU6aRE3SpyNFBpzUXcDINjl7drX_fceGcOkJOm_2XD7PfB6P55dxwrX8ONWC8BPNjCcDGQ9DWYLT76RUiuwTlxdmpqyUnCamMjFbrTBfWUby59Z2BPCBxQd4W6mPcIKdjGSYpLaF0NnySGIlSeZ7rouChRWQBCckS73AT9wFKBde4My9JPFS3wJQTkSdS5wx4-mXATAQFPIfDFGnNRc4h0NsB8wE-QEWxmu4j47reLMF0Wed0Fw7GnqfMvkKabAdQEpcgNxGjmubFqhwnh6wwHEpCWiNJ8u0AruRR6ygESWcEyW2nQcD1z92Of7JdvgCIAv0YFRYclbCBjVawilLqQ4WUM6MF_hUaWtXxZHRC9uTS81BALmcSfqBIziqzlWwyELeo2U_Wq5K_5QRQXCG9eHau6CCsvIdOCcZ4zpWwKAlLlOKb7BnnAvyYBTgLF6-6MC8UETgssb5Tei4lokWreaVlGKgQ77pzBUbpVQ5iwHQBQvJXmhGqA5MGQe2GWi2X1RecUlT2lLVpoaa1BS52mTHWUGivwap24tWry9swyTmFBiwzYXXyDdEsgiSIjkG9FKHMr4slTRUh-2ZFoQu4XKfeS01jQoEbkljIzBxPcfW3P7Dv2vhmkiOVdrI9NCNElyST3YAqe0DHcEgvgMtEl01tmsCdKEtT17FeKprzLQBREISHaE-CFV9Cb0PM0WRDtdSoSY5PihrzTUcaKkqdd2h6itQrwFGKZRZ4KhQenFX2a4bINMPhjqdRIQrKjVjQzo0E7fD7CaKAR3PIFx4vukv-je0gnKW9Kqua27OPYiC25oaq7mGlZC00AUdmBA5O0Py-h3H-3g_ew7f3uIQbr9kitQopwQiBy0W2acqCpLVOR6IMwFSSSu2ZGldgFTVWbRaHtcKBVfpPmXq6RqPzXYXa5avOGc8rOWoCzD55V1fu0dm2LPH2T7ezN5Xm-VquX0z1EXzFDcYxibe78MNCHNakpvw5W27OcQrZfsvwe1xUONAYgU1z3Z1ktO2T3iKHo5L0Txv8A6Ph-3r37VlpfYhjlQHK2tyZS220s42x9W7UnynOTwhcP8kjRrAWAKN-Kqfh7p3Q9NEigo6D7-qgms5oeUFCkMVmt42vK-KCoRwR8Yu_LadvW_Xx80hfIu3ioVjdHzbh-vVfrZehcDJN92mz1BfqsuIcBe1WCnmUHW43UGq2gC2-xj2FRO0ebxaXRF-pvmxpFfCBVUv_hYhtHm1e8aCtI2pbXofjGOx-gF5C13DOu-BcJnKvhVWHMruZqa8tWBkkkAPF0MTLRiZMGj0IxMtGJkIilNc9QE1-y-xYNwbqN1InVG-7c6xtc1NZLec3PbKz77viEaO6I4juu_ojBydO47OfUd35OjecXR7CuCRvbO8LvVN202BjoWD9MeKcdJjHZpEQhNIaALJmURyJpCcCSR3EsmdQJriyZtE8iaQvAmk-STSfAJpPpwqrMYdVna3Qt3K6VZut_K61bxbLbqV362CHnlwyK1A4M0S_to3tArGOcY5loQ1ou7TomXzb6kfdAH93e91Eet1jm2Zvt_-aoPvLoTRFuYdPT9azYwoPtTk225xoge-fr2D7x6-H2jBrbRtW2pUMZ4eb-fAVLAfKsaGYSr79iabj7tpz92Q0I6nX9RtYxwrl0SktfoSl5STtD1N3kaL_nZ7eech1uTyv2fBtFXlpGuF9xG-GP0n2Wl9r5lgb-CqPkeoDHaCT5z-bIdCG6Hfv_8AbyA2rg:1tU5sx:1gQXTzgVSrBSNqzteSiYcKgNNzxzIwUTj2cDQjFzvHs', '2025-01-18 15:16:19.794329', 's3o72ng3j5dmlqagdhvjnkyz0bxfikg3'); alias=default
DEBUG:django.db.backends:(0.000) COMMIT; args=None; alias=default
INFO:django.server:"POST /cotizacion/109/ HTTP/1.1" 200 151410
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/formats.py first seen with mtime 1732569332.0692546
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/session.py first seen with mtime 1732569332.5019946
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/conf/locale/en/__init__.py first seen with mtime 1732569332.0690286
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/cookie.py first seen with mtime 1732569332.5017526
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/storage/fallback.py first seen with mtime 1732569332.5018916
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/anaconda3/lib/python3.11/_strptime.py first seen with mtime 1681948558.9095042
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/sessions/serializers.py first seen with mtime 1732569332.5685349
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/template/context_processors.py first seen with mtime 1732569332.7133355
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/messages/context_processors.py first seen with mtime 1732569332.500866
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/venv/lib/python3.11/site-packages/django/contrib/auth/context_processors.py first seen with mtime 1732569332.2745264
DEBUG:django.utils.autoreload:File /Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py previous mtime: 1736003775.8643882, current mtime: 1736003808.9978824
DEBUG:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py notified as changed. Signal results: [(<function template_changed at 0x106ae8f40>, None), (<function translation_file_changed at 0x10746dbc0>, None)].
INFO:django.utils.autoreload:/Users/andresrdrgz_/Documents/PACIFICO/financiera/pacifico/views.py changed, reloading.
